### ISSUE TITLE
Any chance autoplay?

### ISSUE THREAD

**Issue by ammichael** [LIU9293/react-native-cards-slider#1]
Hello there!

Nice component! Really awesome (:

Is there anyway to implement autoplay..? Or to do it manually?

**Comment by LIU9293** [comment]
Hello Michael, you can take a look inside the index.js, just less than 50 rows. This component itself is just a ScrollView, so it has to "ScrollTo" method that can use for autoplay.
Maybe you can explain why or when you want it to autoplay? Just like a carousel dose?

**Comment by ammichael** [comment]
Hello Liu (hope it is right!)

Yeah, I want it to behave like a carousel. There are some options, but I liked your slider. It would be cool to expose a props like autoplay={true}, that would actually use the scrollTo method of the ScrollView.

Gonna have a look in index.js and maybe try to do this myself and send a Pull Request to you (:

Nice job anyway!

**Comment by LIU9293** [comment]
Please try last version 0.1.2, i hope that is what you looking for.
And, it is not good enough far from now maybe, once you get the end of the image or the view, it just roll back to the first one. Technically, i can add the first element behind the last element then make it like an infinite loop, how do you think about that?
