### ISSUE TITLE
Android image wont show like preview

### ISSUE THREAD

**Issue by stefensuhat** [LIU9293/react-native-cards-slider#3]
At your preview with images or block there is still small piece of next slider shown. but on android there is no preview. check image to be more clear what i mean.

Here is on your preview:

![1](https://cloud.githubusercontent.com/assets/10653041/25908570/b6fe98a0-35d4-11e7-85b6-536801c22cad.png)

Here is what it get on Android:
![screenshot_1494432478](https://cloud.githubusercontent.com/assets/10653041/25908926/c958b44e-35d5-11e7-9acd-015a9604ed7b.png)

How can I get the result same like yours?

Thanks.

**Comment by LIU9293** [comment]
Sorry for late reply, has the problem been solved ?
I didn't checked in Android cause my focus was on IOS, maybe you can fix it and make a PR ?

**Comment by patilrevansidh** [comment]
:+1:

**Comment by Norfeldt** [comment]
I'm also having the same problem with Android (not iOS).. I'm really struggling with styles and have tried to see if was a margin or padding setting that was causing the problem but couldn't find it.

**Comment by LIU9293** [comment]
@Norfeldt Thanks for your reply, I am not maintaining this repo for a long time, but the basic concept of this one is using a scrollview, each slide's width is a little smaller than screen width, and give some space at the beginning and end of the slide.
My suggestion is to try to draw some shapes on paper before make your own component, it should be much easier after you really know what you want to do.

**Comment by Norfeldt** [comment]
@LIU9293 Thank you for taking the time to reply.
I just really like this repo and that is has a smooth scroll snap..
